services:
  artisan:
    build:
      context: .
      dockerfile: dockerfile.artisan
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    networks:
      - internal
  vite:
    build:
      context: .
      dockerfile: dockerfile.vite
    volumes:
      - ".:/app"
    ports:
      - "5173:5173"
  apache:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
    environment:
      - APP_KEY=base64:b/X36sZl1xENbFcGjXDBZtjhdpEvTaVEdPrLhaFuZbc=
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mysql_database
      - DB_USERNAME=mysql_user
      - DB_PASSWORD=mysql_password
      - DB_COLLATION=utf8mb4_unicode_ci 
      - OAUTH_PROVIDER=https://accounts.google.com
      - OAUTH_CLIENT_ID=290798039838-l5jssfu6gh4r66scp2bve1ki7p78l8jl.apps.googleusercontent.com
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "mysql_user", "-pmysql_password", "-e", "SELECT 1"]
      interval: 1s
      timeout: 1s
      retries: 20
    ports:
      - "3306:3306"
networks:
  internal:
    driver: bridge